name: 6-Hour Cloud Virtual Phone

on:
  workflow_dispatch: # Actions tab se manually click karke start karne ke liye

jobs:
  start-vphone:
    runs-on: macos-latest
    timeout-minutes: 360 # Ise 6 ghante (max limit) tak chalne dega
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Android Virtual Device
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: pixel_2
          script: |
            echo "Virtual Phone successfully boot ho gaya hai!"
            adb devices

      - name: Start Web/Terminal Control Session (Tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
